# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miactl < Formula
  desc "Mia Platform Cli for Console"
  homepage "https://www.mia-platform.eu"
  version "0.16.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/mia-platform/miactl/releases/download/v0.16.0/miactl-darwin-amd64"
      sha256 "f4c117c96787927e9cbc4627eecbdb1878be9b0ee0c21f43a652916fd6015012"

      def install
        bin.install "miactl-darwin-amd64" => "miactl"

        chmod 0555, bin/"miactl" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"miactl", "completion")
      end
    end
    on_arm do
      url "https://github.com/mia-platform/miactl/releases/download/v0.16.0/miactl-darwin-arm64"
      sha256 "9c227f18b90fdcc1a827306fadcf46f1efe04e657d7b35dfddb498755acbb04f"

      def install
        bin.install "miactl-darwin-arm64" => "miactl"

        chmod 0555, bin/"miactl" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"miactl", "completion")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mia-platform/miactl/releases/download/v0.16.0/miactl-linux-amd64"
        sha256 "0c7bf57c36d4cbde3b3d97f1e103ad1015bfe8fca92c755bc4f8e63d4311fd8c"

        def install
          bin.install "miactl-linux-amd64" => "miactl"

          chmod 0555, bin/"miactl" # generate_completions_from_executable fails otherwise
          generate_completions_from_executable(bin/"miactl", "completion")
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/mia-platform/miactl/releases/download/v0.16.0/miactl-linux-armv6"
        sha256 "b92834f2dd749bd0c3abb36682e22a2be7928614317be6a514d89f533b10593f"

        def install
          bin.install "miactl-linux-armv6" => "miactl"

          chmod 0555, bin/"miactl" # generate_completions_from_executable fails otherwise
          generate_completions_from_executable(bin/"miactl", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mia-platform/miactl/releases/download/v0.16.0/miactl-linux-arm64"
        sha256 "f3e2b90675de40c90bb779b8d2796f69299f44d3c1f21afc165081dbfd11c833"

        def install
          bin.install "miactl-linux-arm64" => "miactl"

          chmod 0555, bin/"miactl" # generate_completions_from_executable fails otherwise
          generate_completions_from_executable(bin/"miactl", "completion")
        end
      end
    end
  end
end
