# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mlp < Formula
  desc "mlp is a CLI used to interpolate and deploy resource on Kubernetes"
  homepage "https://www.mia-platform.eu"
  version "2.4.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mia-platform/mlp/releases/download/v2.4.2/mlp-darwin-amd64"
      sha256 "2d21d759d25c862786ca3e0900223c3ded5e3ba60675a00cdab58038a7c37e37"

      def install
        bin.install "mlp-darwin-amd64" => "mlp"

        chmod 0555, bin/"mlp" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"mlp", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mia-platform/mlp/releases/download/v2.4.2/mlp-darwin-arm64"
      sha256 "aaceeeac725a827e10975a90b83db71d2b56dfc6ba9906b2e223c0f17033083b"

      def install
        bin.install "mlp-darwin-arm64" => "mlp"

        chmod 0555, bin/"mlp" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"mlp", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mia-platform/mlp/releases/download/v2.4.2/mlp-linux-amd64"
      sha256 "98832e14ee8cba47f0e4e81d3bab1184534bb3c75514d563e25fb8bbbc5ba490"
      def install
        bin.install "mlp-linux-amd64" => "mlp"

        chmod 0555, bin/"mlp" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"mlp", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mia-platform/mlp/releases/download/v2.4.2/mlp-linux-armv6"
      sha256 "7f969968ca0888e0c7a367430512340093b1c2e3c3ba501deb7f201d02926ae5"
      def install
        bin.install "mlp-linux-armv6" => "mlp"

        chmod 0555, bin/"mlp" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"mlp", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mia-platform/mlp/releases/download/v2.4.2/mlp-linux-arm64"
      sha256 "ce8b2dcbe75d5e1da59d2d193b2b3e6d1df980ef8c28999068261626267f452d"
      def install
        bin.install "mlp-linux-arm64" => "mlp"

        chmod 0555, bin/"mlp" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"mlp", "completion")
      end
    end
  end
end
