# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mlp < Formula
  desc "mlp is a CLI used to interpolate and deploy resource on Kubernetes"
  homepage "https://www.mia-platform.eu"
  version "1.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mia-platform/mlp/releases/download/v1.2.1/mlp-darwin-amd64"
      sha256 "d207755b5d41a9c45bb8d30d43b66f50a1bafe9e442d163a99776ea64490a979"

      def install
        bin.install "mlp-darwin-amd64" => "mlp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mia-platform/mlp/releases/download/v1.2.1/mlp-darwin-arm64"
      sha256 "a789964b462abd537ef7a06442b7be74161427a95a723d1107e5ffed6a18c115"

      def install
        bin.install "mlp-darwin-arm64" => "mlp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mia-platform/mlp/releases/download/v1.2.1/mlp-linux-armv6"
      sha256 "1c39db076b5e2df115eb11497adb7404e73f85ee77dfc4c09755c98c065a5edd"

      def install
        bin.install "mlp-linux-armv6" => "mlp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mia-platform/mlp/releases/download/v1.2.1/mlp-linux-amd64"
      sha256 "a27aee52048b2963f2ee117e6e281a2f84c3088413d618eb1c416b36634599bb"

      def install
        bin.install "mlp-linux-amd64" => "mlp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mia-platform/mlp/releases/download/v1.2.1/mlp-linux-arm64"
      sha256 "5a5665d7e775c2595606c86594bb0ee30660124f4b1e2896097e71fe37c29c2b"

      def install
        bin.install "mlp-linux-arm64" => "mlp"
      end
    end
  end
end
