# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vab < Formula
  desc "cli for managing the installation of day 2 operation tools on multiple kubernetes clusters"
  homepage "https://www.mia-platform.eu"
  version "0.10.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/mia-platform/vab/releases/download/v0.10.1/vab-darwin-amd64"
      sha256 "3c86d82b11f900fca9265fe51bda8a07e4424bf0e7bd8053451817f014aa8b5d"

      def install
        bin.install "vab-darwin-amd64" => "vab"

        chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"vab", "completion")
      end
    end
    on_arm do
      url "https://github.com/mia-platform/vab/releases/download/v0.10.1/vab-darwin-arm64"
      sha256 "416eba7a98be907fa7ffc484ccbc8b16e8b10086c3bd7a3a10e0ad12fb3611f7"

      def install
        bin.install "vab-darwin-arm64" => "vab"

        chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"vab", "completion")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mia-platform/vab/releases/download/v0.10.1/vab-linux-amd64"
        sha256 "4a858eecd967a355bba7b6b3ecfbec6da533f513fb1163d6ece0c99c4a54b039"

        def install
          bin.install "vab-linux-amd64" => "vab"

          chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
          generate_completions_from_executable(bin/"vab", "completion")
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/mia-platform/vab/releases/download/v0.10.1/vab-linux-armv6"
        sha256 "dc70dc5c8cc16c34239f870fc4aab9ce52f8d01fd3c6d04b98bb49181ba04cae"

        def install
          bin.install "vab-linux-armv6" => "vab"

          chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
          generate_completions_from_executable(bin/"vab", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mia-platform/vab/releases/download/v0.10.1/vab-linux-arm64"
        sha256 "acbe761f3045a2bf72be885a56bc618bf58e2441fad18e6b56f09ccd9cfeaea0"

        def install
          bin.install "vab-linux-arm64" => "vab"

          chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
          generate_completions_from_executable(bin/"vab", "completion")
        end
      end
    end
  end
end
