# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vab < Formula
  desc "cli for managing the installation of day 2 operation tools on multiple kubernetes clusters"
  homepage "https://www.mia-platform.eu"
  version "0.14.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mia-platform/vab/releases/download/v0.14.0/vab-darwin-amd64"
      sha256 "47c74285747c46f84db98860a10e2862bbc560b187a92f552c5cf19768cf845a"

      def install
        bin.install "vab-darwin-amd64" => "vab"

        chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"vab", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mia-platform/vab/releases/download/v0.14.0/vab-darwin-arm64"
      sha256 "f53a641ed591d14e09e9dbc3d0689073fce7bf8a202af1bbb2d6d858ef3726b4"

      def install
        bin.install "vab-darwin-arm64" => "vab"

        chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"vab", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mia-platform/vab/releases/download/v0.14.0/vab-linux-amd64"
      sha256 "a6634776579b5dadfdae7ea8c4f7932b133d4ff26215d43b9517a1bc522ce8df"
      def install
        bin.install "vab-linux-amd64" => "vab"

        chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"vab", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mia-platform/vab/releases/download/v0.14.0/vab-linux-armv6"
      sha256 "059820b18573ea8961886f585e3b79f85c9e7989e04a0b18b9e9c06b5bcb6a4b"
      def install
        bin.install "vab-linux-armv6" => "vab"

        chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"vab", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mia-platform/vab/releases/download/v0.14.0/vab-linux-arm64"
      sha256 "3ffcff145a15bfba485b49d88e7d1375c35ed724298e660c9bfae7f8a050c0fe"
      def install
        bin.install "vab-linux-arm64" => "vab"

        chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"vab", "completion")
      end
    end
  end
end
