# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vab < Formula
  desc "cli for managing the installation of day 2 operation tools on multiple kubernetes clusters"
  homepage "https://www.mia-platform.eu"
  version "0.13.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mia-platform/vab/releases/download/v0.13.0/vab-darwin-amd64"
      sha256 "b056ed897d44073b5525c080cb5081bbe67814d9ab77379aed330568e5eefffe"

      def install
        bin.install "vab-darwin-amd64" => "vab"

        chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"vab", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mia-platform/vab/releases/download/v0.13.0/vab-darwin-arm64"
      sha256 "b1d365f5cfdee4590f5b7c59c7025dd9c483b97586b2c5df81e69fd25aff4e0a"

      def install
        bin.install "vab-darwin-arm64" => "vab"

        chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"vab", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mia-platform/vab/releases/download/v0.13.0/vab-linux-amd64"
      sha256 "7baa6138fbf7ceca75d37c2ec7df578d288f5f6e266b41859c99ff8278869895"
      def install
        bin.install "vab-linux-amd64" => "vab"

        chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"vab", "completion")
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/mia-platform/vab/releases/download/v0.13.0/vab-linux-armv6"
      sha256 "40973bfa10fbb2aa2f93b5196934a7e65ab1eef75c62a95b6bc359cbd85627f0"
      def install
        bin.install "vab-linux-armv6" => "vab"

        chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"vab", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mia-platform/vab/releases/download/v0.13.0/vab-linux-arm64"
      sha256 "8e07e9a50826097c93d331ece23c2a7aa0b64b66acaf49c3b42e29417e421ec6"
      def install
        bin.install "vab-linux-arm64" => "vab"

        chmod 0555, bin/"vab" # generate_completions_from_executable fails otherwise
        generate_completions_from_executable(bin/"vab", "completion")
      end
    end
  end
end
